### ISSUE TITLE
Astrobery Relays On/Off seem to be the opposite

### ISSUE THREAD

**Issue by AnakChan** [rkaczorek/astroberry-diy#15]
I've just configured the Astroberry Relays for the ASIAir Pro DC Hub and the On/Off toggle switches seem to be opposite to what it is. i.e. On switches off the port, Off switches on the port.

<img width="780" alt="Screen Shot 2021-02-09 at 20 31 49" src="https://user-images.githubusercontent.com/65948942/107364115-fdb64c00-6b15-11eb-894b-48a6a310649e.png">
<img width="779" alt="Screen Shot 2021-02-09 at 20 32 02" src="https://user-images.githubusercontent.com/65948942/107364126-00b13c80-6b16-11eb-8419-548e96c58de8.png">

For now I switched the following and recompiled and it seems to reflect correctly that Off is now switching off the DC port, and On is switching on the DC port :-

gpiod_line_set_value(gpio_relayX, 1);
gpiod_line_set_value(gpio_relayX, 0);

**Comment by AnakChan** [comment]
Update: Please see KenS's fork adding a parity :-

https://github.com/ken-self/astroberry-diy/tree/relays

<img width="782" alt="Screen Shot 2021-02-10 at 18 22 09" src="https://user-images.githubusercontent.com/65948942/107497644-cacf8f00-6bcd-11eb-9ea0-bd616854d6c9.png">

**Comment by rkaczorek** [comment]
I can get it to the upstream if I get pull request. As for now KenS's repo is not available (404)

**Comment by rkaczorek** [comment]
Active state LOW/HIGH added in version 2.7
