### ISSUE TITLE
Change initial value of minimal value of FocusMaxPosN

### ISSUE THREAD

**Issue by jctk** [rkaczorek/astroberry-diy#18]
I am using Astroberry Focuser as a helicoidal focuser for my camera lens.
Max travel of the helicoid is only 117mm and I want to specify 390step for max. position.
The minimum value of max. position is 1000 steps, so I can't set 390.
Therefore I would like to change the position from 1000 steps to 100 steps.

The configuration of the lens and stepper motor is as shown in the attached image.
![IMG_3713](https://user-images.githubusercontent.com/52247294/130612671-ae12ede4-1940-4db0-8d22-b4965eca6d36.jpg)

The stepper motor has 200 steps per revolution and the gears have 60mm per revolution.
The helicoid travel distance of the lens is 117mm, so the max. position is 390step.

To be honest, I have already changed the default value to 100 in my local environment, is it possible to change the original source code as well?

**Comment by rkaczorek** [comment]
It will be changed on the next release
