### ISSUE TITLE
support for different focuser stepper board

### ISSUE THREAD

**Issue by Elfe** [rkaczorek/astroberry-diy#2]
Hi,

it would be awesome if you could add support for a different stepper board for focusing as well.
https://arduino-info.wikispaces.com/SmallSteppers
Currently the only way to use those boards seems to be https://github.com/fehlfarbe/arduino-motorfocus

Thanks
Karsten

**Comment by rkaczorek** [comment]
The driver is designed to support any stepper motor controller, which uses DIR/STEP pins. The one you mention will not be supported by this driver. It requires totally new driver approach to control a stepper motor. Feel free to use parts of my code though.
