### ISSUE TITLE
Support for second A4988 to control filterwheel

### ISSUE THREAD

**Issue by jrsphoto** [rkaczorek/astroberry-diy#21]
What would it take to add support for a second A4988?  My thought would be to use it to control a filter wheel.

**Comment by rkaczorek** [comment]
You can make a copy of indi_astroberry_focuser.xml file located in /usr/share/indi/ and edit it changing "device label" and "driver name". This way you can run two instances of the driver at the same time. Each under its own name.
I cannot guarantee it will work for you as a driver for filter wheel but you can try.

**Comment by rkaczorek** [comment]
Hi, after a while I realized that there is a cleaner way to do this - It can be done with 'Custom Drivers' located in KStars menu Tools/Devices/Custom Drivers. See [this thread](https://indilib.org/forum/ekos/10582-multiple-config-files-for-same-piece-of-equipment.html#76794) on INDI Forum.

**Comment by jrsphoto** [comment]
Thank you very much.  I'll take a look at the link.  I've got a pretty simple raspberry pi hat that I've designed, with support for two A4988 stepper drivers and the temp sensor as well.  

https://easyeda.com/jrsphoto/raspberry-pi-hat-template
