### ISSUE TITLE
Access for compiling and installing Astroberry_focuser driver on RPi4

### ISSUE THREAD

**Issue by pcevey** [rkaczorek/astroberry-diy#22]
Hi,
I would like to use the astroberry_focuser driver with A4988 motor driver on my RPi4, which I already use with kstars/ekos to drive my telescope and cameras. The RPi4 has Ubuntu 20.04 OS.
I tried to follow the instructions in the readme file to compile your driver but I had to register to Gihub to access to astroberry-dyi through <git clone https://github.com/rkaczorek/astroberry-diy.git> (it asks username and password) and once this done, the access was still not permitted because it has new dongle access. 
I am a real beginner in using github software and installing it on my RPi4.

How can I add the astroberry_focuser driver running on Ubuntu 20.04 to my indi library ?
Thanks for the support,
Best regards,
Pierre Cevey

**Comment by rkaczorek** [comment]
Hi Pierre, it is public repository so you don't need any password to access it.

**Comment by pcevey** [comment]
First attempt on my PC asked me dongle access as mentioned . Second attempt worked perfectly fine directly on my Raspberry. 
Sorry for the disturbance.
Thanks !
