### ISSUE TITLE
Standby timer not reset by new command

### ISSUE THREAD

**Issue by keith-b-git** [rkaczorek/astroberry-diy#26]
If standby is enabled and a a move command is given and then a new move command is given within the timer window, standby from the first command will still be activated, possibly preventing the correct execution of later commands.

To reproduce- 
Enable standby and set time to 60s.
Execute a step command.
Execute a second command after 50s

expected result - the motor should not go into standby until 60s after the second command
actual result - the motor goes into standby 60s after the first command and will try to go into standby again 60s after the 2nd, and this  can disrupt a move in process at these times.

Thanks for producing this useful piece of software,

Keith

**Comment by rkaczorek** [comment]
Thanks for reporting. I will take look at it

**Comment by rkaczorek** [comment]
The fix should be pushed to repo in an hour or so. Test and report back.

**Comment by keith-b-git** [comment]
Thanks for your quick response, tested and OK now.
